import type { ResourceDefinition } from '../shared/types/domain.js'

const commonTimestamps = ['createdAt', 'updatedAt']

function findResource(name: string): ResourceDefinition {
  const resource = resources.find((item) => item.name === name)

  if (!resource) {
    throw new Error(`Resource ${name} no configurado`)
  }

  return resource
}

export const resources: ResourceDefinition[] = [
  {
    name: 'approvals',
    route: '/approvals',
    table: 'approvals',
    fields: ['id', 'type', 'status', 'relatedEntityId', 'caseId', 'title', 'requestedBy', 'approverRole', 'amount', 'createdAt', 'resolvedAt'],
    searchableFields: ['title', 'requestedBy', 'approverRole', 'relatedEntityId'],
    filterFields: ['type', 'status', 'caseId'],
    sortFields: ['createdAt', 'resolvedAt', 'amount', 'status'],
  },
  {
    name: 'diagnostic-checklists',
    route: '/diagnostic-checklists',
    table: 'diagnostic_checklists',
    fields: ['id', 'name', 'category', 'description', 'estimatedMinutes', 'items', 'createdAt', 'updatedAt'],
    jsonFields: ['items'],
    searchableFields: ['name', 'category', 'description'],
    filterFields: ['category'],
  },
  {
    name: 'diagnostics',
    route: '/diagnostics',
    table: 'diagnostics',
    fields: ['id', 'caseId', 'category', 'symptoms', 'rootCause', 'severity', 'createdBy', 'updatedBy', 'deletedBy', ...commonTimestamps],
    jsonFields: ['symptoms'],
    searchableFields: ['rootCause', 'category', 'severity', 'createdBy', 'updatedBy'],
    filterFields: ['caseId', 'category', 'severity'],
    sortFields: ['createdAt'],
  },
  {
    name: 'sla-configs',
    route: '/sla/configs',
    table: 'sla_configs',
    fields: ['id', 'name', 'priority', 'targetHours', 'atRiskHours', 'escalationLevel', 'isActive', 'createdAt', 'updatedAt'],
    searchableFields: ['name', 'priority', 'escalationLevel'],
    filterFields: ['priority', 'escalationLevel', 'isActive'],
    sortFields: ['priority', 'targetHours', 'updatedAt'],
  },
  {
    name: 'drivers',
    route: '/drivers',
    table: 'drivers',
    fields: ['id', 'name', 'document', 'phone', 'company', 'license', 'status', 'caseIds', 'createdAt', 'updatedAt'],
    jsonFields: ['caseIds'],
    searchableFields: ['name', 'document', 'phone', 'company', 'license'],
    filterFields: ['status', 'company'],
    sortFields: ['name', 'createdAt', 'status'],
  },
  {
    name: 'driver-documents',
    route: '/driver-documents',
    table: 'driver_documents',
    fields: [
      'id',
      'driverId',
      'documentType',
      'documentNumber',
      'issuedAt',
      'expiresAt',
      'status',
      'attachmentUrl',
      'notes',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    searchableFields: ['driverId', 'documentType', 'documentNumber', 'notes', 'createdBy', 'updatedBy'],
    filterFields: ['driverId', 'documentType', 'status'],
    sortFields: ['expiresAt', 'issuedAt', 'updatedAt'],
  },
  {
    name: 'driver-fines',
    route: '/driver-fines',
    table: 'driver_fines',
    fields: [
      'id',
      'fineNumber',
      'driverId',
      'truckId',
      'incidentId',
      'freightId',
      'fineType',
      'severity',
      'status',
      'occurredAt',
      'location',
      'amount',
      'dueAt',
      'paidAt',
      'description',
      'documentUrl',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    searchableFields: ['fineNumber', 'driverId', 'truckId', 'fineType', 'location', 'description', 'createdBy', 'updatedBy'],
    filterFields: ['driverId', 'truckId', 'status', 'severity', 'fineType'],
    sortFields: ['occurredAt', 'dueAt', 'amount', 'updatedAt'],
  },
  {
    name: 'mechanics',
    route: '/mechanics',
    table: 'mechanics',
    fields: [
      'id',
      'userId',
      'userName',
      'email',
      'roleCode',
      'name',
      'specialtyId',
      'specialty',
      'availability',
      'activeCases',
      'maxCases',
      'shift',
      'createdAt',
      'updatedAt',
    ],
    searchableFields: ['name', 'userName', 'email', 'specialty', 'shift', 'availability'],
    filterFields: ['availability', 'specialty', 'specialtyId', 'userId', 'roleCode'],
    sortFields: ['name', 'activeCases', 'maxCases'],
  },
  {
    name: 'mechanic-specialties',
    route: '/mechanic-specialties',
    table: 'mechanic_specialties',
    fields: ['id', 'code', 'name', 'category', 'description', 'status', 'createdBy', 'updatedBy', 'deletedBy', ...commonTimestamps],
    searchableFields: ['code', 'name', 'category', 'description', 'createdBy', 'updatedBy'],
    filterFields: ['category', 'status'],
    sortFields: ['name', 'category', 'status', 'updatedAt'],
  },
  {
    name: 'customers',
    route: '/customers',
    table: 'customers',
    fields: [
      'id',
      'name',
      'rut',
      'contactName',
      'phone',
      'email',
      'billingAddress',
      'preferredOrigins',
      'preferredDestinations',
      'freightTypes',
      'priceList',
      'creditEnabled',
      'creditLimit',
      'creditUsed',
      'paymentTermsDays',
      'status',
      'riskLevel',
      'notes',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    jsonFields: ['preferredOrigins', 'preferredDestinations', 'freightTypes', 'priceList'],
    searchableFields: ['name', 'rut', 'contactName', 'phone', 'email', 'billingAddress', 'notes', 'createdBy', 'updatedBy'],
    filterFields: ['status', 'creditEnabled', 'riskLevel'],
    sortFields: ['name', 'creditLimit', 'creditUsed', 'paymentTermsDays', 'updatedAt'],
  },
  {
    name: 'communication-profiles',
    route: '/communications/profiles',
    table: 'communication_profiles',
    fields: [
      'id',
      'name',
      'channel',
      'address',
      'ownerName',
      'department',
      'status',
      'isDefault',
      'signature',
      'notes',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    searchableFields: ['name', 'channel', 'address', 'ownerName', 'department', 'notes'],
    filterFields: ['channel', 'status', 'department', 'isDefault'],
    sortFields: ['name', 'channel', 'status', 'updatedAt'],
  },
  {
    name: 'communication-provider-configs',
    route: '/communications/provider-configs',
    table: 'communication_provider_configs',
    fields: [
      'id',
      'name',
      'channel',
      'provider',
      'deliveryMode',
      'profileId',
      'profileName',
      'isActive',
      'fromAddress',
      'whatsappPhoneNumberId',
      'whatsappBusinessAccountId',
      'whatsappAccessToken',
      'whatsappApiVersion',
      'whatsappWebhookVerifyToken',
      'whatsappAppSecret',
      'outlookTenantId',
      'outlookClientId',
      'outlookClientSecret',
      'outlookUserPrincipalName',
      'outlookSaveToSentItems',
      'lastTestAt',
      'lastTestStatus',
      'lastError',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    searchableFields: ['name', 'channel', 'provider', 'profileName', 'fromAddress', 'outlookUserPrincipalName', 'lastError'],
    filterFields: ['channel', 'provider', 'deliveryMode', 'profileId', 'isActive'],
    sortFields: ['updatedAt', 'lastTestAt', 'channel', 'provider'],
  },
  {
    name: 'communication-conversations',
    route: '/communications/conversations',
    table: 'communication_conversations',
    fields: [
      'id',
      'channel',
      'profileId',
      'profileName',
      'contactName',
      'contactAddress',
      'relatedEntityType',
      'relatedEntityId',
      'relatedEntityLabel',
      'subject',
      'status',
      'priority',
      'assignedTo',
      'lastMessageAt',
      'lastMessagePreview',
      'unreadCount',
      'tags',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    jsonFields: ['tags'],
    searchableFields: ['contactName', 'contactAddress', 'subject', 'relatedEntityLabel', 'assignedTo', 'lastMessagePreview'],
    filterFields: ['channel', 'profileId', 'status', 'priority', 'assignedTo', 'relatedEntityType', 'relatedEntityId'],
    sortFields: ['lastMessageAt', 'updatedAt', 'priority', 'unreadCount'],
  },
  {
    name: 'communication-messages',
    route: '/communications/messages',
    table: 'communication_messages',
    fields: [
      'id',
      'conversationId',
      'channel',
      'profileId',
      'direction',
      'status',
      'fromName',
      'fromAddress',
      'toName',
      'toAddress',
      'subject',
      'body',
      'sentAt',
      'deliveredAt',
      'readAt',
      'errorMessage',
      'attachments',
      'provider',
      'providerConfigId',
      'providerMessageId',
      'providerStatus',
      'sentByIntegration',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    jsonFields: ['attachments'],
    searchableFields: ['fromName', 'fromAddress', 'toName', 'toAddress', 'subject', 'body', 'status', 'provider', 'providerMessageId', 'providerStatus'],
    filterFields: ['conversationId', 'channel', 'profileId', 'direction', 'status', 'provider', 'providerConfigId', 'providerMessageId'],
    sortFields: ['sentAt', 'createdAt', 'status', 'providerStatus'],
  },
  {
    name: 'communication-quote-links',
    route: '/communications/quote-links',
    table: 'communication_quote_links',
    fields: [
      'id',
      'conversationId',
      'quoteType',
      'quoteId',
      'quoteNumber',
      'customerName',
      'status',
      'total',
      'linkedBy',
      'notes',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    searchableFields: ['quoteNumber', 'customerName', 'status', 'linkedBy', 'notes'],
    filterFields: ['conversationId', 'quoteType', 'quoteId', 'status', 'customerName'],
    sortFields: ['createdAt', 'updatedAt', 'total'],
  },
  {
    name: 'notifications',
    route: '/notifications',
    table: 'notifications',
    fields: [
      'id',
      'title',
      'message',
      'category',
      'severity',
      'status',
      'sourceModule',
      'relatedEntityType',
      'relatedEntityId',
      'relatedEntityLabel',
      'actionPath',
      'assignedTo',
      'dueAt',
      'readAt',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    searchableFields: ['title', 'message', 'category', 'sourceModule', 'relatedEntityLabel', 'assignedTo'],
    filterFields: ['category', 'severity', 'status', 'sourceModule', 'assignedTo', 'relatedEntityType'],
    sortFields: ['createdAt', 'updatedAt', 'dueAt', 'severity', 'status'],
  },
  {
    name: 'alert-subscriptions',
    route: '/notifications/subscriptions',
    table: 'alert_subscriptions',
    fields: [
      'id',
      'userId',
      'userName',
      'channel',
      'sourceModule',
      'eventType',
      'severity',
      'deliveryTarget',
      'isEnabled',
      'quietHoursStart',
      'quietHoursEnd',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    searchableFields: ['userName', 'channel', 'sourceModule', 'eventType', 'severity', 'deliveryTarget'],
    filterFields: ['userId', 'channel', 'sourceModule', 'eventType', 'severity', 'isEnabled'],
    sortFields: ['updatedAt', 'createdAt', 'sourceModule', 'severity'],
  },
  {
    name: 'trucks',
    route: '/trucks',
    table: 'trucks',
    fields: ['id', 'plate', 'brand', 'model', 'year', 'odometer', 'status', 'vin', 'lastServiceAt', 'createdAt', 'updatedAt'],
    searchableFields: ['plate', 'brand', 'model', 'vin'],
    filterFields: ['status', 'brand'],
    sortFields: ['plate', 'year', 'odometer', 'lastServiceAt'],
  },
  {
    name: 'fleet-trucks',
    route: '/fleet/trucks',
    table: 'fleet_trucks',
    fields: [
      'id',
      'plate',
      'brand',
      'model',
      'year',
      'vin',
      'chassisNumber',
      'engineNumber',
      'loadCapacityKg',
      'bodyType',
      'currentOdometer',
      'operationalStatus',
      'fuelType',
      'acquisitionDate',
      'acquisitionCost',
      'ownerType',
      'assignedDriverId',
      'assignedDriverName',
      'nextFreightId',
      'nextFreightAt',
      'estimatedAvailableAt',
      'mainBlocker',
      'notes',
      ...commonTimestamps,
    ],
    searchableFields: ['plate', 'brand', 'model', 'vin', 'assignedDriverName', 'mainBlocker'],
    filterFields: ['operationalStatus', 'fuelType', 'ownerType', 'assignedDriverId'],
    sortFields: ['plate', 'currentOdometer', 'acquisitionDate', 'updatedAt'],
  },
  {
    name: 'fleet-availability',
    route: '/fleet/availability',
    table: 'fleet_availability',
    fields: ['id', 'truckId', 'column', 'blockerReason', 'availableAt', ...commonTimestamps],
    searchableFields: ['truckId', 'column', 'blockerReason'],
    filterFields: ['truckId', 'column'],
  },
  {
    name: 'truck-health-scores',
    route: '/fleet/health-scores',
    table: 'truck_health_scores',
    fields: ['id', 'truckId', 'score', 'status', 'deductions', 'summary', ...commonTimestamps],
    jsonFields: ['deductions'],
    searchableFields: ['truckId', 'status', 'summary'],
    filterFields: ['truckId', 'status'],
    sortFields: ['score', 'updatedAt'],
  },
  {
    name: 'truck-timeline-events',
    route: '/fleet/timeline-events',
    table: 'truck_timeline_events',
    fields: ['id', 'truckId', 'eventType', 'title', 'description', 'relatedEntityType', 'relatedEntityId', 'eventDate', 'createdBy', 'createdAt'],
    searchableFields: ['title', 'description', 'eventType', 'createdBy'],
    filterFields: ['truckId', 'eventType', 'relatedEntityType'],
    sortFields: ['eventDate', 'createdAt'],
  },
  {
    name: 'freight-requests',
    route: '/freight/requests',
    table: 'freight_requests',
    fields: [
      'id',
      'requestNumber',
      'trackingNumber',
      'customerId',
      'customerName',
      'customerPhone',
      'customerEmail',
      'originAddress',
      'destinationAddress',
      'estimatedKm',
      'cargoType',
      'cargoDescription',
      'weightKg',
      'volumeM3',
      'requiresWaitingTime',
      'waitingHours',
      'requiresLoadingHelp',
      'requiresUnloadingHelp',
      'requestedPickupDate',
      'pickupWindow',
      'packageCount',
      'coverageZone',
      'availabilityStatus',
      'estimatedDurationText',
      'observations',
      'status',
      'quoteId',
      'assignedTruckId',
      'assignedDriverId',
      ...commonTimestamps,
    ],
    searchableFields: ['requestNumber', 'trackingNumber', 'customerId', 'customerName', 'originAddress', 'destinationAddress', 'cargoDescription'],
    filterFields: ['status', 'cargoType', 'customerId', 'assignedTruckId', 'assignedDriverId', 'availabilityStatus'],
    sortFields: ['createdAt', 'updatedAt', 'requestedPickupDate', 'estimatedKm'],
  },
  {
    name: 'freight-quotes',
    route: '/freight/quotes',
    table: 'freight_quotes',
    fields: [
      'id',
      'quoteNumber',
      'requestId',
      'customerId',
      'customerName',
      'estimatedKm',
      'cargoType',
      'baseRate',
      'kmRate',
      'waitingCost',
      'loadingCost',
      'unloadingCost',
      'cargoTypeSurcharge',
      'fuelCost',
      'fuelLiters',
      'tollCost',
      'operationCost',
      'marginAmount',
      'dieselPricePerLiter',
      'fuelKmPerLiter',
      'operationCostPerKm',
      'pricingConfigId',
      'pricingSnapshot',
      'routePricingSnapshot',
      'subtotal',
      'taxAmount',
      'total',
      'validUntil',
      'status',
      'sentBy',
      'sentAt',
      'approvedAt',
      'rejectedAt',
      ...commonTimestamps,
    ],
    jsonFields: ['pricingSnapshot', 'routePricingSnapshot'],
    searchableFields: ['quoteNumber', 'customerId', 'customerName', 'requestId'],
    filterFields: ['status', 'cargoType', 'customerId', 'requestId'],
    sortFields: ['validUntil', 'total', 'createdAt'],
  },
  {
    name: 'freight-pricing-settings',
    route: '/freight/pricing-settings',
    table: 'freight_pricing_settings',
    fields: [
      'id',
      'name',
      'active',
      'currencyCode',
      'baseRate',
      'dieselPricePerLiter',
      'fuelKmPerLiter',
      'operationCostPerKm',
      'waitingHourRate',
      'loadingHelpCost',
      'unloadingHelpCost',
      'tollMarkupPercent',
      'marginPercent',
      'taxPercent',
      'cargoSurcharges',
      'createdBy',
      'updatedBy',
      ...commonTimestamps,
    ],
    jsonFields: ['cargoSurcharges'],
    searchableFields: ['name', 'currencyCode', 'createdBy', 'updatedBy'],
    filterFields: ['active', 'currencyCode'],
    sortFields: ['updatedAt', 'createdAt', 'baseRate', 'dieselPricePerLiter'],
  },
  {
    name: 'freight-assignments',
    route: '/freight/assignments',
    table: 'freight_assignments',
    fields: ['id', 'requestId', 'quoteId', 'truckId', 'driverId', 'assignedBy', 'pickupDate', 'deliveryDate', 'status', 'notes', 'createdBy', 'updatedBy', 'deletedBy', ...commonTimestamps],
    searchableFields: ['requestId', 'quoteId', 'truckId', 'driverId', 'assignedBy', 'notes', 'createdBy', 'updatedBy'],
    filterFields: ['status', 'truckId', 'driverId'],
    sortFields: ['pickupDate', 'deliveryDate', 'createdAt'],
  },
  {
    name: 'driver-trip-sheets',
    route: '/driver-trip-sheets',
    table: 'driver_trip_sheets',
    fields: [
      'id',
      'sheetNumber',
      'freightId',
      'requestId',
      'quoteId',
      'assignmentId',
      'driverId',
      'driverName',
      'truckId',
      'truckPlate',
      'customerId',
      'customerName',
      'originAddress',
      'destinationAddress',
      'tripDate',
      'deliveredAt',
      'kmPlanned',
      'kmReal',
      'revenue',
      'fuelCost',
      'tollCost',
      'mealCost',
      'tipCost',
      'parkingCost',
      'lodgingCost',
      'otherCost',
      'waitingHours',
      'waitingCost',
      'totalExpenses',
      'grossMargin',
      'netMargin',
      'costPerKm',
      'revenuePerKm',
      'performanceScore',
      'status',
      'expenseItems',
      'notes',
      'createdBy',
      'updatedBy',
      'deletedBy',
      ...commonTimestamps,
    ],
    jsonFields: ['expenseItems'],
    searchableFields: [
      'sheetNumber',
      'freightId',
      'requestId',
      'quoteId',
      'assignmentId',
      'driverName',
      'truckPlate',
      'customerName',
      'originAddress',
      'destinationAddress',
      'status',
      'notes',
      'createdBy',
      'updatedBy',
    ],
    filterFields: ['status', 'driverId', 'truckId', 'customerId', 'requestId', 'assignmentId'],
    sortFields: ['tripDate', 'deliveredAt', 'totalExpenses', 'netMargin', 'costPerKm', 'performanceScore', 'waitingHours', 'updatedAt'],
  },
  {
    name: 'freight-profitability',
    route: '/freight-profitability',
    table: 'freight_profitability',
    fields: [
      'id',
      'freightId',
      'truckId',
      'driverId',
      'customerName',
      'revenue',
      'fuelCost',
      'tollCost',
      'driverCost',
      'tireWearCost',
      'maintenanceAllocatedCost',
      'otherCosts',
      'totalCost',
      'grossMargin',
      'netMargin',
      'marginPercentage',
      'km',
      'costPerKm',
      'revenuePerKm',
      ...commonTimestamps,
    ],
    searchableFields: ['freightId', 'truckId', 'driverId', 'customerName'],
    filterFields: ['truckId', 'driverId'],
    sortFields: ['grossMargin', 'marginPercentage', 'costPerKm', 'createdAt'],
  },
  {
    name: 'fuel-records',
    route: '/fuel/records',
    table: 'fuel_records',
    fields: ['id', 'truckId', 'driverId', 'date', 'liters', 'pricePerLiter', 'totalAmount', 'odometer', 'stationName', 'receiptNumber', 'attachmentUrl', 'kmPerLiter', 'deviationStatus', 'notes', ...commonTimestamps],
    searchableFields: ['truckId', 'driverId', 'stationName', 'receiptNumber', 'notes'],
    filterFields: ['truckId', 'driverId', 'deviationStatus'],
    sortFields: ['date', 'totalAmount', 'liters', 'odometer'],
  },
  {
    name: 'fuel-price-snapshots',
    route: '/fuel/prices/cache',
    table: 'fuel_price_snapshots',
    fields: [
      'id',
      'provider',
      'source',
      'fuelType',
      'normalizedFuelType',
      'regionCode',
      'regionName',
      'pricePerLiter',
      'sourceDate',
      'year',
      'month',
      'raw',
      'status',
      'lastFetchedAt',
      'errorMessage',
      ...commonTimestamps,
    ],
    jsonFields: ['raw'],
    searchableFields: ['provider', 'source', 'fuelType', 'normalizedFuelType', 'regionName', 'errorMessage'],
    filterFields: ['provider', 'fuelType', 'normalizedFuelType', 'regionCode', 'status'],
    sortFields: ['lastFetchedAt', 'sourceDate', 'pricePerLiter', 'updatedAt'],
  },
  {
    name: 'incidents',
    route: '/incidents',
    table: 'incidents',
    fields: ['id', 'incidentNumber', 'truckId', 'driverId', 'freightId', 'workshopCaseId', 'incidentType', 'severity', 'description', 'occurredAt', 'location', 'estimatedCost', 'status', 'documents', 'photos', 'notes', ...commonTimestamps],
    jsonFields: ['documents', 'photos'],
    searchableFields: ['incidentNumber', 'truckId', 'driverId', 'freightId', 'workshopCaseId', 'description', 'location', 'notes'],
    filterFields: ['truckId', 'driverId', 'freightId', 'workshopCaseId', 'incidentType', 'severity', 'status'],
    sortFields: ['occurredAt', 'estimatedCost', 'severity', 'status', 'updatedAt'],
  },
  {
    name: 'labor-tasks',
    route: '/labor/tasks',
    table: 'labor_tasks',
    fields: ['id', 'caseId', 'description', 'estimatedHours', 'realHours', 'mechanicId', 'mechanicName', 'hourlyRate', 'status', ...commonTimestamps],
    searchableFields: ['description', 'mechanicName', 'caseId'],
    filterFields: ['caseId', 'mechanicId', 'status'],
    sortFields: ['estimatedHours', 'realHours', 'updatedAt'],
  },
  {
    name: 'parts',
    route: '/parts',
    table: 'parts',
    fields: ['id', 'sku', 'name', 'category', 'stock', 'minStock', 'unitCost', 'createdBy', 'updatedBy', 'deletedBy', ...commonTimestamps],
    searchableFields: ['sku', 'name', 'category', 'createdBy', 'updatedBy', 'deletedBy'],
    filterFields: ['category'],
    sortFields: ['sku', 'name', 'stock', 'unitCost'],
  },
  {
    name: 'roles',
    route: '/permissions/roles',
    table: 'roles',
    fields: ['id', 'code', 'name', 'description', 'permissions', ...commonTimestamps],
    jsonFields: ['permissions'],
    searchableFields: ['code', 'name', 'description'],
    filterFields: ['code'],
  },
  {
    name: 'user-role-assignments',
    route: '/permissions/user-roles',
    table: 'user_role_assignments',
    fields: ['id', 'userId', 'userName', 'email', 'roleCode', 'passwordHash', 'passwordUpdatedAt', 'isActive', ...commonTimestamps],
    searchableFields: ['userName', 'email', 'roleCode'],
    filterFields: ['roleCode', 'isActive'],
  },
  {
    name: 'shortcut-preferences',
    route: '/settings/shortcuts',
    table: 'shortcut_preferences',
    fields: [
      'id',
      'userId',
      'profile',
      'moduleCycleShortcut',
      'quickActionShortcut',
      'globalShortcutsEnabled',
      'quickActionsEnabled',
      'moduleCyclingEnabled',
      'shortcutHintsEnabled',
      'createdBy',
      'updatedBy',
      ...commonTimestamps,
    ],
    searchableFields: ['userId', 'profile', 'moduleCycleShortcut', 'quickActionShortcut', 'createdBy', 'updatedBy'],
    filterFields: ['userId', 'profile', 'moduleCycleShortcut', 'quickActionShortcut'],
    sortFields: ['updatedAt', 'createdAt'],
  },
  {
    name: 'preventive-maintenance-plans',
    route: '/preventive-maintenance/plans',
    table: 'preventive_maintenance_plans',
    fields: ['id', 'truckId', 'maintenanceType', 'description', 'frequencyType', 'everyKm', 'everyDays', 'lastDoneAt', 'lastDoneOdometer', 'nextDueAt', 'nextDueOdometer', 'riskStatus', 'assignedTo', 'notes', ...commonTimestamps],
    searchableFields: ['description', 'truckId', 'assignedTo', 'notes'],
    filterFields: ['truckId', 'maintenanceType', 'frequencyType', 'riskStatus'],
    sortFields: ['nextDueAt', 'nextDueOdometer', 'riskStatus', 'updatedAt'],
  },
  {
    name: 'purchase-orders',
    route: '/purchase-orders',
    table: 'purchase_orders',
    fields: ['id', 'purchaseOrderNumber', 'supplierName', 'status', 'relatedCaseId', 'requestedBy', 'approvedBy', 'items', 'totalEstimated', 'expectedDeliveryDate', 'createdBy', 'updatedBy', 'deletedBy', ...commonTimestamps],
    jsonFields: ['items'],
    searchableFields: ['purchaseOrderNumber', 'supplierName', 'requestedBy', 'approvedBy', 'createdBy', 'updatedBy'],
    filterFields: ['status', 'relatedCaseId', 'supplierName'],
    sortFields: ['createdAt', 'expectedDeliveryDate', 'totalEstimated'],
  },
  {
    name: 'purchase-requests',
    route: '/purchase-requests',
    table: 'purchase_requests',
    fields: ['id', 'caseId', 'partId', 'sku', 'name', 'quantity', 'requestedBy', 'status', 'purchaseOrderId', 'createdAt', 'updatedAt'],
    searchableFields: ['sku', 'name', 'requestedBy', 'caseId'],
    filterFields: ['caseId', 'partId', 'status', 'purchaseOrderId'],
    sortFields: ['createdAt', 'quantity'],
  },
  {
    name: 'quotes',
    route: '/quotes',
    table: 'quotes',
    fields: ['id', 'quoteNumber', 'caseId', 'caseNumber', 'customerId', 'customerName', 'diagnosisSummary', 'status', 'items', 'total', 'createdAt', 'expiresAt', 'approvedBy', 'updatedAt'],
    jsonFields: ['items'],
    searchableFields: ['quoteNumber', 'caseNumber', 'customerId', 'customerName', 'diagnosisSummary'],
    filterFields: ['caseId', 'customerId', 'status'],
    sortFields: ['createdAt', 'expiresAt', 'total'],
  },
  {
    name: 'repair-solutions',
    route: '/repair-solutions',
    table: 'repair_solutions',
    fields: ['id', 'caseId', 'summary', 'requiredParts', 'laborHours', 'estimatedCost', 'approvalRequired', ...commonTimestamps],
    jsonFields: ['requiredParts'],
    searchableFields: ['caseId', 'summary'],
    filterFields: ['caseId', 'approvalRequired'],
    sortFields: ['estimatedCost', 'laborHours', 'updatedAt'],
  },
  {
    name: 'schedule-events',
    route: '/schedule/events',
    table: 'schedule_events',
    fields: ['id', 'caseId', 'caseNumber', 'title', 'customerName', 'truckPlate', 'date', 'startsAt', 'endsAt', 'estimatedHours', 'priority', 'slaStatus', 'hasPartsBlock', 'mechanicId', 'mechanicName', 'bayId', 'bayName', 'status', ...commonTimestamps],
    searchableFields: ['caseNumber', 'title', 'customerName', 'truckPlate', 'mechanicName', 'bayName'],
    filterFields: ['date', 'bayId', 'mechanicId', 'status', 'priority', 'slaStatus'],
    sortFields: ['date', 'startsAt', 'estimatedHours'],
  },
  {
    name: 'waiting-queue',
    route: '/schedule/waiting-queue',
    table: 'waiting_queue',
    fields: ['id', 'caseId', 'caseNumber', 'customerName', 'priority', 'truckPlate', 'slaStatus', 'hasPartsBlock', 'requestedAt', 'reason', 'estimatedHours', ...commonTimestamps],
    searchableFields: ['caseNumber', 'customerName', 'truckPlate', 'reason'],
    filterFields: ['priority', 'slaStatus', 'hasPartsBlock'],
    sortFields: ['requestedAt', 'estimatedHours'],
  },
  {
    name: 'suppliers',
    route: '/suppliers',
    table: 'suppliers',
    fields: [
      'id',
      'name',
      'rut',
      'contactName',
      'phone',
      'email',
      'categories',
      'averageDeliveryDays',
      'rating',
      'activePurchaseOrderIds',
      'status',
      'notes',
      'createdBy',
      'updatedBy',
      ...commonTimestamps,
    ],
    jsonFields: ['categories', 'activePurchaseOrderIds'],
    searchableFields: ['name', 'rut', 'contactName', 'phone', 'email', 'notes'],
    filterFields: ['status'],
    sortFields: ['name', 'rating', 'averageDeliveryDays'],
  },
  {
    name: 'telematics',
    route: '/telematics',
    table: 'truck_telemetry',
    fields: ['id', 'truckId', 'latitude', 'longitude', 'speed', 'odometer', 'fuelLevel', 'engineStatus', 'lastSignalAt', 'idleMinutes', 'alerts', ...commonTimestamps],
    jsonFields: ['alerts'],
    searchableFields: ['truckId', 'engineStatus'],
    filterFields: ['truckId', 'engineStatus'],
    sortFields: ['lastSignalAt', 'speed', 'fuelLevel'],
  },
  {
    name: 'tire-lifecycles',
    route: '/tire-performance/tires',
    table: 'tire_lifecycles',
    fields: ['id', 'skuId', 'skuCode', 'skuName', 'purchaseOrderId', 'supplierId', 'supplierName', 'truckId', 'truckPlate', 'brand', 'model', 'tireSize', 'tireType', 'usageType', 'tirePosition', 'purchaseCost', 'purchaseDate', 'installedAt', 'odometerAtInstall', 'removedAt', 'odometerAtRemoval', 'kmUsed', 'costPerKm', 'removalReason', 'status', 'caseId', 'notes', 'createdBy', 'updatedBy', 'deletedBy', ...commonTimestamps],
    searchableFields: ['skuCode', 'skuName', 'supplierName', 'truckPlate', 'brand', 'model', 'notes', 'createdBy', 'updatedBy'],
    filterFields: ['tireType', 'supplierName', 'brand', 'truckId', 'tirePosition', 'usageType', 'status', 'removalReason'],
    sortFields: ['purchaseDate', 'purchaseCost', 'installedAt', 'removedAt', 'costPerKm'],
  },
  {
    name: 'departure-checklists',
    route: '/trip-checklists/departures',
    table: 'trip_departure_checklists',
    fields: ['id', 'freightId', 'truckId', 'driverId', 'departureAt', 'odometerStart', 'fuelLevelStart', 'tiresOk', 'lightsOk', 'brakesOk', 'oilOk', 'waterOk', 'documentsOk', 'cargoSecured', 'photos', 'observations', 'status', ...commonTimestamps],
    jsonFields: ['photos'],
    searchableFields: ['freightId', 'truckId', 'driverId', 'observations'],
    filterFields: ['freightId', 'truckId', 'driverId', 'status'],
    sortFields: ['departureAt', 'odometerStart'],
  },
  {
    name: 'arrival-checklists',
    route: '/trip-checklists/arrivals',
    table: 'trip_arrival_checklists',
    fields: ['id', 'freightId', 'truckId', 'driverId', 'arrivalAt', 'odometerEnd', 'fuelLevelEnd', 'newDamages', 'cargoStatus', 'receiverName', 'receiverSignatureUrl', 'photos', 'observations', 'status', ...commonTimestamps],
    jsonFields: ['photos'],
    searchableFields: ['freightId', 'truckId', 'driverId', 'cargoStatus', 'receiverName', 'observations'],
    filterFields: ['freightId', 'truckId', 'driverId', 'status', 'newDamages'],
    sortFields: ['arrivalAt', 'odometerEnd'],
  },
  {
    name: 'truck-costs',
    route: '/truck-costs',
    table: 'truck_costs',
    fields: ['id', 'truckId', 'costType', 'description', 'amount', 'date', 'relatedEntityType', 'relatedEntityId', 'odometer', 'notes', ...commonTimestamps],
    searchableFields: ['truckId', 'costType', 'description', 'relatedEntityId', 'notes'],
    filterFields: ['truckId', 'costType', 'relatedEntityType', 'relatedEntityId'],
    sortFields: ['date', 'amount', 'odometer'],
  },
  {
    name: 'truck-cost-summaries',
    route: '/truck-costs/summaries',
    table: 'truck_cost_summaries',
    fields: ['id', 'truckId', 'monthlyCost', 'costPerKm', 'freightCostAverage', 'workshopCost', 'profitabilityStatus', ...commonTimestamps],
    searchableFields: ['truckId', 'profitabilityStatus'],
    filterFields: ['truckId', 'profitabilityStatus'],
    sortFields: ['monthlyCost', 'costPerKm', 'updatedAt'],
  },
  {
    name: 'truck-documents',
    route: '/truck-documents',
    table: 'truck_documents',
    fields: ['id', 'truckId', 'documentType', 'documentNumber', 'issuedAt', 'expiresAt', 'status', 'attachmentUrl', 'notes', 'createdBy', 'updatedBy', 'deletedBy', ...commonTimestamps],
    searchableFields: ['truckId', 'documentType', 'documentNumber', 'notes', 'createdBy', 'updatedBy'],
    filterFields: ['truckId', 'documentType', 'status'],
    sortFields: ['expiresAt', 'issuedAt', 'updatedAt'],
  },
  {
    name: 'warehouse-locations',
    route: '/warehouse/locations',
    table: 'warehouse_locations',
    fields: ['id', 'code', 'name', 'zone', 'aisle', 'shelf', 'level', 'capacity', 'status', 'createdBy', 'updatedBy', ...commonTimestamps],
    searchableFields: ['code', 'name', 'zone', 'aisle', 'shelf', 'level', 'createdBy', 'updatedBy'],
    filterFields: ['zone', 'status'],
    sortFields: ['code', 'capacity', 'updatedAt'],
  },
  {
    name: 'warehouse-stock',
    route: '/warehouse/stock',
    table: 'warehouse_stock',
    fields: ['id', 'partId', 'sku', 'name', 'quantity', 'locationId', 'locationCode', 'minStock', 'status', ...commonTimestamps],
    searchableFields: ['sku', 'name', 'locationCode'],
    filterFields: ['partId', 'locationId', 'status'],
    sortFields: ['sku', 'quantity', 'minStock'],
  },
  {
    name: 'warehouse-managers',
    route: '/warehouse/managers',
    table: 'warehouse_managers',
    fields: ['id', 'name', 'phone', 'shift', 'activeCases', 'assignedLocationIds', ...commonTimestamps],
    jsonFields: ['assignedLocationIds'],
    searchableFields: ['name', 'phone', 'shift'],
    filterFields: ['shift'],
    sortFields: ['name', 'activeCases'],
  },
  {
    name: 'warehouse-movements',
    route: '/warehouse/movements',
    table: 'warehouse_movements',
    fields: ['id', 'partSku', 'partName', 'type', 'quantity', 'locationCode', 'relatedCaseId', 'createdAt', 'createdBy', 'updatedAt'],
    searchableFields: ['partSku', 'partName', 'locationCode', 'createdBy'],
    filterFields: ['type', 'locationCode', 'relatedCaseId'],
    sortFields: ['createdAt', 'quantity'],
  },
  {
    name: 'workshop-bays',
    route: '/bays',
    table: 'workshop_bays',
    fields: ['id', 'name', 'type', 'status', 'currentCaseId', 'currentCaseNumber', ...commonTimestamps],
    searchableFields: ['name', 'type', 'currentCaseNumber'],
    filterFields: ['type', 'status'],
    sortFields: ['name', 'updatedAt'],
  },
]

export const scheduleEventResource = findResource('schedule-events')
export const approvalResource = findResource('approvals')
export const diagnosticResource = findResource('diagnostics')
export const customerResource = findResource('customers')
export const driverResource = findResource('drivers')
export const fleetAvailabilityResource = findResource('fleet-availability')
export const fleetTruckResource = findResource('fleet-trucks')
export const freightAssignmentResource = findResource('freight-assignments')
export const driverTripSheetResource = findResource('driver-trip-sheets')
export const freightQuoteResource = findResource('freight-quotes')
export const fuelPriceSnapshotResource = findResource('fuel-price-snapshots')
export const freightPricingSettingsResource = findResource('freight-pricing-settings')
export const freightRequestResource = findResource('freight-requests')
export const partResource = findResource('parts')
export const purchaseOrderResource = findResource('purchase-orders')
export const quoteResource = findResource('quotes')
export const repairSolutionResource = findResource('repair-solutions')
export const supplierResource = findResource('suppliers')
export const truckResource = findResource('trucks')
export const truckDocumentResource = findResource('truck-documents')
export const truckHealthScoreResource = findResource('truck-health-scores')
export const truckTimelineEventResource = findResource('truck-timeline-events')
export const tireLifecycleResource = findResource('tire-lifecycles')
export const truckCostResource = findResource('truck-costs')
export const waitingQueueResource = findResource('waiting-queue')
export const warehouseLocationResource = findResource('warehouse-locations')
export const workshopBayResource = findResource('workshop-bays')
export const mechanicResource = findResource('mechanics')
export const mechanicSpecialtyResource = findResource('mechanic-specialties')
export const roleResource = findResource('roles')
export const shortcutPreferenceResource = findResource('shortcut-preferences')
export const userRoleAssignmentResource = findResource('user-role-assignments')

export const workshopCaseResource: ResourceDefinition = {
  name: 'workshop-cases',
  route: '/workshop-cases',
  table: 'workshop_cases',
  fields: [
    'id',
    'caseNumber',
    'code',
    'truckId',
    'truckPlate',
    'driverId',
    'driverName',
    'customerId',
    'customerName',
    'customer',
    'failureDescription',
    'title',
    'intakeSource',
    'intakeLocation',
    'reportedByName',
    'reportedByPhone',
    'odometerAtEntry',
    'failureCategory',
    'symptoms',
    'safetyImpact',
    'immobilized',
    'diagnosisRequested',
    'serviceType',
    'downtimeImpact',
    'status',
    'priority',
    'assignedMechanicId',
    'mechanicId',
    'mechanicName',
    'warehouseManagerId',
    'warehouseManagerName',
    'slaId',
    'slaDueAt',
    'slaStatus',
    'escalationLevel',
    'escalationReason',
    'requiredParts',
    'purchaseRequestIds',
    'createdAt',
    'updatedAt',
    'estimatedDeliveryAt',
    'estimatedCost',
    'currentStep',
    'closeReason',
    'closureSummary',
    'closedAt',
    'closedBy',
  ],
  jsonFields: ['requiredParts', 'purchaseRequestIds', 'symptoms'],
  searchableFields: [
    'caseNumber',
    'code',
    'truckPlate',
    'driverName',
    'customerId',
    'customerName',
    'failureDescription',
    'title',
    'mechanicName',
    'intakeLocation',
    'reportedByName',
    'failureCategory',
    'diagnosisRequested',
  ],
  filterFields: ['status', 'priority', 'slaStatus', 'mechanicId', 'truckId', 'driverId', 'customerId', 'escalationLevel', 'failureCategory', 'intakeSource', 'immobilized', 'safetyImpact'],
  sortFields: ['createdAt', 'updatedAt', 'slaDueAt', 'estimatedDeliveryAt', 'estimatedCost', 'priority', 'closedAt'],
}

export const assignmentResource: ResourceDefinition = {
  name: 'assignments',
  route: '/assignments',
  table: 'assignments',
  fields: ['id', 'caseId', 'caseCode', 'mechanicId', 'mechanicName', 'status', 'assignedAt', 'createdAt', 'updatedAt'],
  searchableFields: ['caseCode', 'mechanicName', 'caseId', 'mechanicId'],
  filterFields: ['caseId', 'mechanicId', 'status'],
  sortFields: ['assignedAt', 'createdAt'],
}

export const escalationEventResource: ResourceDefinition = {
  name: 'escalation-events',
  route: '/escalations',
  table: 'escalation_events',
  fields: ['id', 'caseId', 'fromLevel', 'toLevel', 'reason', 'comment', 'createdAt', 'createdBy', 'updatedAt'],
  searchableFields: ['caseId', 'reason', 'comment', 'createdBy'],
  filterFields: ['caseId', 'toLevel', 'reason'],
  sortFields: ['createdAt'],
}

export const allCrudResources = [workshopCaseResource, assignmentResource, escalationEventResource, ...resources]
